In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('class_ipl_22-26_dataset_with_nulls.csv')

In [7]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5.0,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,NaN,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2.0,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6.0,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6.0,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [8]:
df.shape

(367, 25)

In [9]:
df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets      12
team2_runs          0
team2_wickets       0
winner              7
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     5
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

In [10]:
df.isnull()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
363,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
mean_df = df.copy()

In [18]:
mean_val = mean_df['team1_runs'].mean()
print(mean_val)

185.0708446866485

In [20]:
mean_df['team1_runs']=mean_df['team1_runs'].fillna(mean_val)
mean_df['team1_runs'].isnull().sum()

np.int64(0)

In [30]:
team_1null = df['team1_wickets'].isnull()

abc = df['team1_wickets'].mean()

In [33]:
df['team1_wickets']=df['team1_wickets'].fillna(abc)

In [ ]:
print(mean)

In [24]:
print(team_1null)

0      False
1       True
2      False
3      False
4      False
       ...
362     True
363    False
364    False
365    False
366    False
Name: team1_wickets, Length: 367, dtype: bool

In [35]:
mean_df.isnull()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
363,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
365,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
366,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [77]:
df.isnull().sum()

date               0
season             0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             7
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    5
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64

In [37]:
 median_df = df.copy()

In [39]:
median_df.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players'],
      dtype='object')

In [40]:
median_df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5.000000,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,6.242254,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2.000000,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6.000000,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6.000000,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [42]:
median_df.isnull().sum()

date               0
season             0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             7
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    5
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64

In [50]:
num_columns = median_df.select_dtypes(include='number').columns
print(num_columns)

Index(['season', 'team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit'],
      dtype='object')

In [78]:
median_df[num_columns].isnull().sum()

season            0
team1_runs        0
team1_wickets     0
team2_runs        0
team2_wickets     0
win_by_runs       0
win_by_wickets    0
overs_limit       0
dtype: int64

In [54]:
median_df[num_columns] = median_df[num_columns].isnull().median()

/tmp/ipykernel_461/1050389572.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  median_df[num_columns] = median_df[num_columns].isnull().median()

In [55]:
median_df[num_columns].isnull().sum()

season            0
team1_runs        0
team1_wickets     0
team2_runs        0
team2_wickets     0
win_by_runs       0
win_by_wickets    0
overs_limit       0
dtype: int64

In [80]:
mode_df = df.copy()

In [81]:
mode_df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5.000000,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,6.242254,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2.000000,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6.000000,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6.000000,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [82]:
num1 = mode_df.select_dtypes(include='number').columns
print(num1)

Index(['season', 'team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit'],
      dtype='object')

In [86]:
mode_df['season'] = mode_df['season'].isnull().mode()

In [89]:
mode1 = df['season'].mode()
print(mode1)

0    2022
1    2023
2    2025
3    2026
Name: season, dtype: int64

In [90]:
mode_df.isnull().sum()

date                 0
season             366
city                 0
venue                0
team1                0
team2                0
toss_winner          0
toss_decision        0
team1_runs           0
team1_wickets        0
team2_runs           0
team2_wickets        0
winner               7
result_type          0
win_by_runs          0
win_by_wickets       0
player_of_match      5
match_referee        0
umpire1              0
umpire2              0
tv_umpire            0
reserve_umpire       0
overs_limit          0
team1_players        0
team2_players        0
dtype: int64

In [91]:
from sklearn.impute import SimpleImputer

In [92]:
df1 = df.copy()

In [93]:
df1.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5.000000,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,6.242254,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2.000000,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6.000000,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6.000000,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [97]:
df1.isnull().sum()

date               0
season             0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             7
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    5
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64

In [104]:
impute1 = SimpleImputer(strategy='mean')
impute2 = SimpleImputer(strategy='median')
impute3 = SimpleImputer(strategy='most_frequent')

In [110]:
df1['team1_runs'] = impute1.fit_transform(df1[['team1_runs']])

In [111]:
df1['team1_wickets']= impute2.fit_transform(df1[['team1_wickets']])

In [107]:
print(type(df1[['team1_wickets']]))

<class 'pandas.core.frame.DataFrame'>

In [109]:
num1 = df1.select_dtypes(include='number')
print(num1)

     season  team1_runs  team1_wickets  team2_runs  team2_wickets  \
0      2022       131.0       5.000000         133              4
1      2022       177.0       6.242254         179              6
2      2022       205.0       2.000000         208              5
3      2022       158.0       6.000000         161              5
4      2022       210.0       6.000000         149              7
..      ...         ...            ...         ...            ...
362    2026       203.0       6.242254         163             10
363    2026       254.0       5.000000         162             10
364    2026       243.0       8.000000         196             10
365    2026       214.0       6.000000         219              3
366    2026       155.0       8.000000         161              5

     win_by_runs  win_by_wickets  overs_limit
0              0               6           20
1              0               4           20
2              0               5           20
3              0               5           20
4             61               0           20
..           ...             ...          ...
362           40               0           20
363           92               0           20
364           47               0           20
365            0               7           20
366            0               5           20

[367 rows x 8 columns]