<a href="https://colab.research.google.com/github/mayur07699/MLDS/blob/main/labelencoding17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('/content/class_ipl_22-26_dataset.csv')

In [3]:
df

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,24-05-2026,2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,203,5,...,0,Kuldeep Yadav,IR Siddiqui,K Swaroopanand,HAS Khalid,SJ Nogajski,M Krishnadas,20,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G..."
363,26-05-2026,2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,254,5,...,0,RM Patidar,J Srinath,J Madanagopal,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,20,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J..."
364,27-05-2026,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,243,8,...,0,V Suryavanshi,V Narayan Kutty,AT Holdstock,UV Gandhe,R Pandit,SJ Nogajski,20,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish..."
365,29-05-2026,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,214,6,...,7,Shubman Gill,Prakash Bhatt,R Pandit,SJ Nogajski,AT Holdstock,UV Gandhe,20,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,..."
366,31-05-2026,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,155,8,...,5,V Kohli,J Srinath,KN Ananthapadmanabhan,Nitin Menon,J Madanagopal,VK Sharma,20,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat..."

In [4]:
df.isnull().sum()

date               0
season             0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             7
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    5
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64

In [5]:
df.head(10)

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."
5,30-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,128,10,...,3,PWH de Silva,M Nayyar,J Madanagopal,Navdeep Singh,Nitin Menon,Chirra Ravikanthreddy,20,"AM Rahane, VR Iyer, SS Iyer, N Rana, SP Narine...","F du Plessis, Anuj Rawat, V Kohli, DJ Willey, ..."
6,31-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Chennai Super Kings,Lucknow Super Giants,Lucknow Super Giants,field,210,7,...,6,E Lewis,J Srinath,RJ Tucker,VK Sharma,YC Barde,NA Patwardhan,20,"RV Uthappa, RD Gaikwad, MM Ali, S Dube, AT Ray...","KL Rahul, Q de Kock, MK Pandey, E Lewis, DJ Ho..."
7,01-04-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,137,10,...,6,UT Yadav,Prakash Bhatt,AK Chaudhary,HAS Khalid,J Madanagopal,A Totre,20,"MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living...","AM Rahane, VR Iyer, SS Iyer, SW Billings, N Ra..."
8,02-04-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Gujarat Titans,Delhi Capitals,Delhi Capitals,field,171,6,...,0,LH Ferguson,Shakti Singh,KN Ananthapadmanabhan,UV Gandhe,BNJ Oxenford,Vinod Seshan,20,"MS Wade, Shubman Gill, V Shankar, HH Pandya, D...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
9,02-04-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Rajasthan Royals,Mumbai Indians,Mumbai Indians,field,193,8,...,0,JC Buttler,DS Manohar,Nitin Menon,PG Pathak,VK Sharma,N Pandit,20,"JC Buttler, YBK Jaiswal, D Padikkal, SV Samson...","Ishan Kishan, RG Sharma, Anmolpreet Singh, Til..."

In [7]:
lb = LabelEncoder()
df['Winner_encoded']= lb.fit_transform(df['winner'])

In [9]:
mapping = pd.DataFrame({
    'Winner': lb.classes_,
    'Encoded_value':range(len(lb.classes_))
})
mapping

                         Winner  Encoded_value
0           Chennai Super Kings              0
1                Delhi Capitals              1
2                Gujarat Titans              2
3         Kolkata Knight Riders              3
4          Lucknow Super Giants              4
5                Mumbai Indians              5
6                  Punjab Kings              6
7              Rajasthan Royals              7
8   Royal Challengers Bangalore              8
9   Royal Challengers Bengaluru              9
10          Sunrisers Hyderabad             10
11                          NaN             11