<a href="https://colab.research.google.com/github/mayur07699/MLDS/blob/main/Ordinal_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv("/content/IPLPlayerStat-1.csv")

In [5]:
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0

In [18]:
def player_form(avg):
  if avg <= 10:
    return "poor"
  elif avg <= 15:
    return "average"
  elif avg <= 20:
    return "good"
  elif avg <= 25:
    return "very good"
  else:
    return "excellent"
df['Player_Form'] = df['batting_avg'].apply(player_form)
df[['player','batting_avg','Player_Form']].head()

           player  batting_avg Player_Form
0  A Ashish Reddy        10.00        poor
1        A Badoni        14.64     average
2      A Chandila         0.33        poor
3        A Chopra         8.83        poor
4     A Choudhary         5.00        poor

In [19]:
df

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings,Player_Form
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0,poor
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0,average
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0,poor
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0,poor
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0,poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,600,Yash Dayal,0,0,1,11.0,205.0,296.0,9,0.00,0.00,0.00,8.66,26.91,18.64,1.0,0.0,poor
601,601,Yashpal Singh,47,5,67,0.0,0.0,0.0,4,11.75,70.15,7.46,0.00,0.00,0.00,3.0,0.0,average
602,602,Younis Khan,3,0,7,0.0,0.0,0.0,1,3.00,42.86,0.00,0.00,0.00,0.00,1.0,0.0,poor
603,603,Yuvraj Singh,2754,367,2207,36.0,882.0,1091.0,129,21.35,124.78,16.63,7.42,30.31,24.50,29.0,0.0,very good
604,604,Z Khan,117,13,141,102.0,2276.0,2860.0,99,1.18,82.98,9.22,7.54,28.04,22.31,20.0,0.0,poor

In [21]:
df['Player_Form'].unique()

array(['poor', 'average', 'very good', 'good', 'excellent'], dtype=object)

In [24]:
encoder = OrdinalEncoder(
    categories = [['poor', 'average', 'very good', 'good', 'excellent']]
)
df['Player_Form_encoded']=encoder.fit_transform(df[['Player_Form']]).astype(int)
df[['player','batting_avg','Player_Form_encoded']].head()

           player  batting_avg  Player_Form_encoded
0  A Ashish Reddy        10.00                    0
1        A Badoni        14.64                    1
2      A Chandila         0.33                    0
3        A Chopra         8.83                    0
4     A Choudhary         5.00                    0

In [25]:
df['Player_Form_encoded'].unique()

array([0, 1, 2, 3, 4])

In [28]:
df[['player','batting_avg','Player_Form','Player_Form_encoded']].head(15)

            player  batting_avg Player_Form  Player_Form_encoded
0   A Ashish Reddy        10.00        poor                    0
1         A Badoni        14.64     average                    1
2       A Chandila         0.33        poor                    0
3         A Chopra         8.83        poor                    0
4      A Choudhary         5.00        poor                    0
5      A Dananjaya         4.00        poor                    0
6       A Flintoff        20.67   very good                    2
7         A Kumble         0.83        poor                    0
8        A Manohar        15.43        good                    3
9         A Mishra         2.35        poor                    0
10        A Mithun         2.12        poor                    0
11        A Mukund         9.50        poor                    0
12         A Nehra         0.47        poor                    0
13        A Nortje         0.27        poor                    0
14         A Singh         0.09        poor                    0

In [ ]:
df[[]]