<a href="https://colab.research.google.com/github/mayur07699/MLDS/blob/main/ridgee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression,Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_squared_error

In [8]:
df = pd.read_csv('/content/IPL_2008_-_2026-Lasso.csv')

In [9]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,reserve_umpire,overs_limit,team1_players,team2_players,team1_wickets_remaining,team2_run_rate,total_wickets_fell,run_margin_dup,wicket_margin_dup,team2_runs_x2
0,18-04-2008,2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,82,10,...,VN Kulkarni,20,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",0,11.10,13,140.0,0.0,444.0
1,19-04-2008,2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",6,12.00,9,33.0,0.0,480.0
2,19-04-2008,2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,132,1,...,Unknown,20,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",9,6.45,9,0.0,9.0,258.0
3,20-04-2008,2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,112,5,...,F Gomes,20,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",5,5.50,15,0.0,5.0,220.0
4,20-04-2008,2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,165,7,...,SN Bandekar,20,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",3,8.30,12,0.0,5.0,332.0

In [11]:
df.shape

(1218, 31)

In [12]:
df.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players', 'team1_wickets_remaining',
       'team2_run_rate', 'total_wickets_fell', 'run_margin_dup',
       'wicket_margin_dup', 'team2_runs_x2'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     1218 non-null   object
 1   season                   1218 non-null   object
 2   city                     1218 non-null   object
 3   venue                    1218 non-null   object
 4   team1                    1218 non-null   object
 5   team2                    1218 non-null   object
 6   toss_winner              1218 non-null   object
 7   toss_decision            1218 non-null   object
 8   team1_runs               1218 non-null   int64
 9   team1_wickets            1218 non-null   int64
 10  team2_runs               1218 non-null   int64
 11  team2_wickets            1218 non-null   int64
 12  winner                   1218 non-null   object
 13  result_type              1218 non-null   object
 14  win_by_runs              1218 non-null   int64
 15  win_by_wickets           1218 non-null   int64
 16  player_of_match          1218 non-null   object
 17  match_referee            1218 non-null   object
 18  umpire1                  1218 non-null   object
 19  umpire2                  1218 non-null   object
 20  tv_umpire                1218 non-null   object
 21  reserve_umpire           1218 non-null   object
 22  overs_limit              1218 non-null   int64
 23  team1_players            1218 non-null   object
 24  team2_players            1218 non-null   object
 25  team1_wickets_remaining  1218 non-null   int64
 26  team2_run_rate           1218 non-null   float64
 27  total_wickets_fell       1218 non-null   int64
 28  run_margin_dup           1218 non-null   float64
 29  wicket_margin_dup        1218 non-null   float64
 30  team2_runs_x2            1218 non-null   float64
dtypes: float64(4), int64(9), object(18)
memory usage: 295.1+ KB

In [28]:
numeric_col = df.select_dtypes(include='number').columns
print(numeric_col)

Index(['team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit',
       'team1_wickets_remaining', 'team2_run_rate', 'total_wickets_fell',
       'run_margin_dup', 'wicket_margin_dup', 'team2_runs_x2'],
      dtype='object')

In [58]:
num = ['team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit',
       'team1_wickets_remaining', 'team2_run_rate', 'total_wickets_fell',
       'run_margin_dup', 'wicket_margin_dup', 'team2_runs_x2']
categories_cols = ["team1", "team2", "venue", "city", "toss_winner",
"toss_decision",
"season", "player_of_match"]
X = pd.get_dummies(
    df[num + categories_cols],
    columns=categories_cols,
    drop_first=True
)
Y = df['team1_runs']
print("Final feature matrix shape:", X.shape)
print("Number of rows (matches):", len(df))

Final feature matrix shape: (1218, 501)
Number of rows (matches): 1218

In [38]:
print(type(categories_cols))
print(categories_cols)

<class 'list'>
['team1', 'team2', 'venue', 'city', 'toss_winner', 'toss_decision', 'season', 'player_of_match']

In [39]:
df.shape

(1218, 31)

In [41]:
X.shape

(1218, 501)

In [42]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,reserve_umpire,overs_limit,team1_players,team2_players,team1_wickets_remaining,team2_run_rate,total_wickets_fell,run_margin_dup,wicket_margin_dup,team2_runs_x2
0,18-04-2008,2008,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,82,10,...,VN Kulkarni,20,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",0,11.10,13,140.0,0.0,444.0
1,19-04-2008,2008,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",6,12.00,9,33.0,0.0,480.0
2,19-04-2008,2008,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,132,1,...,Unknown,20,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",9,6.45,9,0.0,9.0,258.0
3,20-04-2008,2008,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,112,5,...,F Gomes,20,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",5,5.50,15,0.0,5.0,220.0
4,20-04-2008,2008,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,165,7,...,SN Bandekar,20,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",3,8.30,12,0.0,5.0,332.0

In [57]:
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size= 0.25,random_state=42)
scalar = StandardScaler()
X_train_s = scalar.fit_transform(X_train)
X_test_s = scalar.fit_transform(X_test)
print("Train shape",X_train_s.shape)
print("Train shape:", X_train_s.shape)
print("Test shape :", X_test_s.shape)

Train shape (913, 501)
Train shape: (913, 501)
Test shape : (305, 501)

In [49]:
lr = LinearRegression()
lr.fit(X_train_s,Y_train)
lr_train_r2 = r2_score(Y_train, lr.predict(X_train_s))
lr_test_r2 = r2_score(Y_test,lr.predict(X_test_s))
lr_gap = lr_train_r2 -lr_test_r2
print(lr_gap)

0.02290711525691458

In [59]:
#Ridgee
lambdas = np.array([0.1, 1, 5, 10, 20, 100, 200, 300, 500, 800, 1000, 1500, 2000, 3000])

train_scores = []
test_scores = []

for alpha in lambdas:
    ridge = Ridge(alpha=alpha)
    ridge.fit(X_train_s, Y_train)

    train_pred = ridge.predict(X_train_s)
    test_pred = ridge.predict(X_test_s)

    train_scores.append(r2_score(Y_train, train_pred))
    test_scores.append(r2_score(Y_test, test_pred))

result = pd.DataFrame({
    "lambda": lambdas,
    "train_r2": train_scores,
    "test_r2": test_scores
})

print(f"Linear Regression -> Train R2: {lr_train_r2:.4f}")
print(f"Linear Regression -> Test  R2: {lr_test_r2:.4f}")
print(f"Train - Test gap (overfitting signal): {lr_gap:.4f}")

Linear Regression -> Train R2: 1.0000
Linear Regression -> Test  R2: 0.9771
Train - Test gap (overfitting signal): 0.0229

In [56]:
from sklearn.linear_model import RidgeCV
from sklearn.metrics import r2_score
import numpy as np

# Candidate alpha values
alphas = np.array([0.1, 1, 5, 10, 20, 100, 200, 300, 500, 800, 1000, 1500, 2000, 3000])

# Ridge Regression with Cross-Validation
ridge_cv = RidgeCV(alphas=alphas, cv=5)
ridge_cv.fit(X_train_s, Y_train)

# Best alpha selected by the model
print("Best lambda (alpha):", ridge_cv.alpha_)

# Predictions
train_pred = ridge_cv.predict(X_train_s)
test_pred = ridge_cv.predict(X_test_s)

# R² scores
print("Train R²:", r2_score(Y_train, train_pred))
print("Test R²:", r2_score(Y_test, test_pred))

Best lambda (alpha): 0.1
Train R²: 0.9999999164525657
Test R²: 0.9771852190103872

In [ ]:
rdige_best = Ridge(alpha=)